# Generated by Django 2.0.3 on 2018-10-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empprofile',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
