# Generated by Django 2.0.3 on 2018-12-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_auto_20181230_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empprofile',
            name='emp_id',
            field=models.AutoField(default='10000', primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
